version: '3'

tasks:
  generate-licenses:
    cmds:
      - bunx generate-license-file --input package.json --output ./embed/THIRD-PARTY-LICENSES.txt --overwrite --omit-versions --ci

  vp:
    cmds:
      - npm version {{.VERSION}} --sign-git-tag
      - git push
      - git push —-tags origin
      - bun publish
    requires:
      vars:
        - VERSION
