name: Release

permissions:
  contents: write

on:
  release:
    types: [published]

jobs:
  compile:
    continue-on-error: true
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            name: linux-x64
          - os: ubuntu-22.04-arm
            name: linux-aarch64
          - os: macos-15-intel
            name: macos-x86_64
          - os: macos-26
            name: macos-aarch64
          - os: windows-2025
            name: windows-x86_64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Install Task
        uses: go-task/setup-task@v1
      - name: Install Packages
        run: bun install --production
      - name: Compile
        run: task compile
      - name: Rename Archive
        run: |
          $version = (Get-Content package.json | ConvertFrom-Json).version
          if (Test-Path "./packaged/crop4mkv.7z") {
            Move-Item "./packaged/crop4mkv.7z" "./packaged/crop4mkv-$version-${{ matrix.name }}.7z"
          }
          if (Test-Path "./packaged/crop4mkv.tar.xz") {
            Move-Item "./packaged/crop4mkv.tar.xz" "./packaged/crop4mkv-$version-${{ matrix.name }}.tar.xz"
          }
        shell: pwsh
      - name: Upload Binary
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./packaged/crop4mkv-*
        
